//@version=5
strategy('Bollinger Band Buy and MA/Sell/Stop Loss', overlay=true)

// ボリンジャーバンドのパラメーター
length = input.int(20, minval=1)
mult = input.float(2.0, minval=0.001, maxval=50)

// 移動平均線のパラメーター
ma_length = input.int(100, minval=1)

// ストップロスのパラメーター
stop_loss_pct = input.int(4, minval=0, maxval=100)

// 購入条件のパラメーター
buy_adjustment_pct = input.float(0.5, minval=0.1, maxval=10)
buy_adjustment_days = input.int(5, minval=1, maxval=30)

// ボリンジャーバンドを計算
basis = ta.sma(close, length)
dev = mult * ta.stdev(close, length)
upper = basis + dev
lower = basis - dev

// 変数の初期化
var buy_signal = false
var buy_adjustment_counter = 0
var globalState = array.new_float(2)

// -2σに到達したら買い注文を出す
if close <= lower
    buy_adjustment_counter := buy_adjustment_counter + 1
    buy_signal := true
    label.new(bar_index, high, str.tostring(buy_adjustment_counter))

// bgcolor(buy_signal ? color.red : na, transp=90)
// plotchar(close, 'Bar Index', '', location=location.top)

plotchar(close, 'close', '', location=location.top)
plotchar(close[1], "close 1", location=location.top)

// if buy_signal and close >= lower * (1 - buy_adjustment_pct / 100)
//    label.new(bar_index, high, '5%未満')

// 購入条件を追加
// if buy_signal and buy_adjustment_counter < buy_adjustment_days and close >= lower * (1 - buy_adjustment_pct / 100)
//     buy_adjustment_counter += 1
//     buy_adjustment_counter

// if buy_adjustment_counter >= buy_adjustment_days
//     strategy.entry('Buy', strategy.long)

// // 100日移動平均線に到達したら売り注文を出す
// if close >= ta.sma(close, ma_length)
//     strategy.close('Buy')

// // ストップロス - 株価が-4%に達したら売り注文を出す
// if strategy.position_size > 0 and close <= strategy.position_avg_price * (1 - stop_loss_pct / 100)
//     strategy.close('Buy')

// プロット
plot(basis, 'Basis', color=color.new(color.blue, 0))
p1 = plot(upper, 'Upper', color=color.new(color.green, 0))
p2 = plot(lower, 'Lower', color=color.new(color.red, 0))
fill(p1, p2, color=color.new(color.green, 90))
